/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stockvaluer;

import java.awt.Color;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class page extends javax.swing.JFrame {

    /**
     * Creates new form page
     */
    public page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        EPS_text = new javax.swing.JTextField();
        return_label = new javax.swing.JLabel();
        return_text = new javax.swing.JTextField();
        EPS_label = new javax.swing.JLabel();
        rate_label = new javax.swing.JLabel();
        pe_text = new javax.swing.JTextField();
        value_label = new javax.swing.JLabel();
        rate_text = new javax.swing.JTextField();
        Button = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        years_text = new javax.swing.JTextField();
        years_label = new javax.swing.JLabel();
        pe_label = new javax.swing.JLabel();
        explaination = new javax.swing.JLabel();
        value_decimal = new javax.swing.JLabel();
        return__ = new javax.swing.JLabel();
        EPS__ = new javax.swing.JLabel();
        rate__ = new javax.swing.JLabel();
        pe__ = new javax.swing.JLabel();
        years__ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stock Valuer");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(66, 188, 66));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("v.1.0    Created by Amali Delauney");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(452, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 399, 640, 35);

        EPS_text.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        EPS_text.setForeground(new java.awt.Color(102, 102, 102));
        EPS_text.setToolTipText("Current EPS (earnings per share)");
        EPS_text.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(EPS_text);
        EPS_text.setBounds(70, 150, 90, 36);

        return_label.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        return_label.setText("% Return");
        jPanel1.add(return_label);
        return_label.setBounds(220, 220, 120, 30);

        return_text.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        return_text.setForeground(new java.awt.Color(102, 102, 102));
        return_text.setText("15");
        return_text.setToolTipText("return on investment");
        return_text.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(return_text);
        return_text.setBounds(220, 250, 50, 36);

        EPS_label.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        EPS_label.setText("EPS");
        jPanel1.add(EPS_label);
        EPS_label.setBounds(70, 120, 50, 30);

        rate_label.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        rate_label.setText("EPS Growth %");
        jPanel1.add(rate_label);
        rate_label.setBounds(220, 120, 160, 30);

        pe_text.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        pe_text.setForeground(new java.awt.Color(102, 102, 102));
        pe_text.setToolTipText("estimated future P/E");
        pe_text.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(pe_text);
        pe_text.setBounds(420, 150, 90, 38);

        value_label.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        value_label.setText("VALUE:");
        jPanel1.add(value_label);
        value_label.setBounds(70, 320, 200, 40);

        rate_text.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        rate_text.setForeground(new java.awt.Color(102, 102, 102));
        rate_text.setToolTipText("Current EPS growth rate");
        rate_text.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(rate_text);
        rate_text.setBounds(220, 150, 90, 38);

        Button.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        Button.setText("Calculate");
        Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Button);
        Button.setBounds(420, 250, 110, 40);

        jPanel3.setBackground(new java.awt.Color(66, 188, 66));

        jLabel1.setBackground(new java.awt.Color(66, 188, 66));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SIMPLE STOCK VALUER");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stockvaluer/FPD_stocks_small.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(140, 140, 140))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 756, 100);

        years_text.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        years_text.setForeground(new java.awt.Color(102, 102, 102));
        years_text.setText("10");
        years_text.setToolTipText("");
        years_text.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        years_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                years_textActionPerformed(evt);
            }
        });
        jPanel1.add(years_text);
        years_text.setBounds(70, 250, 50, 36);

        years_label.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        years_label.setText("# Years");
        jPanel1.add(years_label);
        years_label.setBounds(70, 220, 90, 30);

        pe_label.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        pe_label.setText("Future P/E");
        jPanel1.add(pe_label);
        pe_label.setBounds(420, 120, 160, 30);

        explaination.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jPanel1.add(explaination);
        explaination.setBounds(70, 370, 530, 20);

        value_decimal.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        value_decimal.setForeground(new java.awt.Color(0, 204, 0));
        jPanel1.add(value_decimal);
        value_decimal.setBounds(200, 320, 440, 40);

        return__.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        return__.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(return__);
        return__.setBounds(210, 230, 10, 10);

        EPS__.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        EPS__.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(EPS__);
        EPS__.setBounds(60, 130, 10, 10);

        rate__.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        rate__.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(rate__);
        rate__.setBounds(210, 130, 10, 10);

        pe__.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        pe__.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(pe__);
        pe__.setBounds(410, 130, 10, 10);

        years__.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        years__.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(years__);
        years__.setBounds(60, 230, 10, 10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(653, 469));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActionPerformed
        
        EPS__.setText("");
        rate__.setText("");
        pe__.setText("");
        return__.setText("");
        years__.setText("");
        
        eps = Double.NaN;
        rate = Double.NaN;
        n = Double.NaN;
        f_pe = Double.NaN;
        f_eps = Double.NaN;
        f_price = Double.NaN;
        ann_return = Double.NaN;
        value = Double.NaN;
        
        try
        {
            eps = Double.parseDouble(EPS_text.getText());
            rate = Double.parseDouble(rate_text.getText());
            f_pe = Double.parseDouble(pe_text.getText());
            ann_return = Double.parseDouble(return_text.getText());
            n = Double.parseDouble(years_text.getText());
            
            f_eps = eps * Math.pow((1 + (rate/100)), n);
            f_price = f_eps * f_pe;
            value = f_price / Math.pow((1 + (ann_return/100)), n);
            
            value_decimal.setText("$" + format.format(value));
            explaination.setText("To achieve " + ann_return + "% growth in " + n +
                                    " years, current price should be $" + format.format(value));
            explaination.setForeground(Color.blue);
        }
        catch (NumberFormatException e)
        {
            try{Double.parseDouble(EPS_text.getText());}
            catch(NumberFormatException c0){EPS__.setText("*");}
            
            try{Double.parseDouble(rate_text.getText());}
            catch(NumberFormatException c0){rate__.setText("*");}
            
            try{Double.parseDouble(pe_text.getText());}
            catch(NumberFormatException c0){pe__.setText("*");}
            
            try{Double.parseDouble(return_text.getText());}
            catch(NumberFormatException c0){return__.setText("*");}
            
            try{Double.parseDouble(years_text.getText());}
            catch(NumberFormatException c0){years__.setText("*");}
            
            explaination.setText("Please enter valid numbers");
            explaination.setForeground(Color.red);
        }
    }//GEN-LAST:event_ButtonActionPerformed

    private void years_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_years_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_years_textActionPerformed
    
    DecimalFormat format = new DecimalFormat("0.00");
    double eps, rate, n, f_pe, f_eps, f_price, ann_return, value;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button;
    private javax.swing.JLabel EPS__;
    private javax.swing.JLabel EPS_label;
    private javax.swing.JTextField EPS_text;
    private javax.swing.JLabel explaination;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel pe__;
    private javax.swing.JLabel pe_label;
    private javax.swing.JTextField pe_text;
    private javax.swing.JLabel rate__;
    private javax.swing.JLabel rate_label;
    private javax.swing.JTextField rate_text;
    private javax.swing.JLabel return__;
    private javax.swing.JLabel return_label;
    private javax.swing.JTextField return_text;
    private javax.swing.JLabel value_decimal;
    private javax.swing.JLabel value_label;
    private javax.swing.JLabel years__;
    private javax.swing.JLabel years_label;
    private javax.swing.JTextField years_text;
    // End of variables declaration//GEN-END:variables
}
